### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by rasbt** [cdwanze/cdwanze.github.io#7]
Hi there,
can you please take down the PDF

https://github.com/cdwanze/cdwanze.github.io/blob/master/电脑/python/机器学习/Python%20Machine%20Learning.pdf

within the next 5 days since it violates the copyright of this work.

I was just notified by this and it would be nice if you could remove it without having to involve the publisher, GitHub staff, and filing a DCMA claim.

Thanks.

**Comment by a358003542** [comment]
that is no problem. thanks your comment.

**Comment by a358003542** [comment]
@rasbt if there does have any other pdfs have the copyright issue, please tell. best wishes. in the future the website will have less pdfs which is just simply drop into it.

**Comment by rasbt** [comment]
Thanks, I appreciate it! I don't know about other PDFs, since a reader notified me about this particular one only. However, books typically have a statement somewhere on the first few pages, e.g., in this case:

> Copyright © 2016 Packt Publishing
All rights reserved. No part of this book may be reproduced, stored in a retrieval system, or transmitted in any form or by any means, without the prior written permission of the publisher, except in the case of brief quotations embedded in critical articles or reviews.
